# Generated by Django 6.0.3 on 2026-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Control',
                'verbose_name_plural': 'Control',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games.game',),
        ),
        migrations.AddField(
            model_name='game',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='games/screenshots/'),
        ),
        migrations.AddField(
            model_name='game',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='games/screenshots/'),
        ),
    ]
