# Generated by Django 6.0.3 on 2026-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_android_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.TextField(blank=True, default='', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='android_type',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('joinplay', 'Joinplay'), ('apk', 'APK')], default='', help_text='Clasifica el juego para las secciones Android, Joinplay o APK.', max_length=20, verbose_name='Tipo Android'),
        ),
    ]
