# Generated by Django 6.0.3 on 2026-04-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_category_options_alter_game_options_game_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='Enlace')),
                ('icon_class', models.CharField(blank=True, help_text='Clase de FontAwesome (ej: fab fa-instagram)', max_length=100, verbose_name='Clase de Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
    ]
