# Generated by Django 6.0.3 on 2026-04-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='Imagen de Icono'),
        ),
    ]
