[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn saya_tienda.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
