AVAILABLE_TAGS = [
    "2d game", "2dcg", "3d game", "3dcg", "adventure", "ahegao", "ai cg", "anal sex",
    "animated", "apk", "bdsm", "bestiality", "big ass", "big tits", "blackmail",
    "bukkake", "censored", "character creation", "cheating", "combat", "corruption",
    "cosplay", "creampie", "dating sim", "dilf", "drugs", "dystopian setting",
    "exhibitionism", "fantasy", "female domination", "female protagonist", "footjob",
    "furry", "futa/trans", "futa/trans protagonist", "futari", "gay", "graphic violence",
    "groping", "group sex", "handjob", "harem", "horror", "humiliation", "humor",
    "incest", "internal view", "interracial", "Interspecies Sex", "japanese game",
    "JoiPlay", "kinetic novel", "lactation", "lesbian", "loli", "maid", "male domination",
    "male protagonist", "management", "masturbation", "milf", "mind control",
    "mobile game", "monster", "monster girl", "multiple endings", "multiple penetration",
    "multiple protagonist", "necrophilia", "netorare", "netorase", "netori", "ntr",
    "oral sex", "paranormal", "paranormal romance", "parody", "platformer",
    "point & click", "possession", "pov", "pregnancy", "prostitution", "puzzle",
    "rape", "real porn", "religion", "romance", "rpg", "sandbox", "scat",
    "school setting", "sci-fi", "sex change", "sex toys", "sexual harassment",
    "shooter", "shota", "side-scroller", "simulator", "sissification", "slave",
    "sleep sex", "spanking", "strategy", "stripping", "superpowers", "Suscriptor",
    "swinging", "teasing", "tentacles", "time stop", "tiny breasts", "titfuck",
    "trainer", "transformation", "trap", "turn based combat", "turn-based combat",
    "twins", "upper-class girl", "urination", "vaginal sex", "virgin", "VN",
    "voiced", "vore", "voyeurism"
]
